name: _
publish_to: none
environment:
  sdk: ^3.8.0
workspace:
  - packages/http_firestore_redirect
  - packages/http_redirect
  - packages/http_redirect_client_browser_test
  - packages/http_redirect_test
  - repo_support
