name: tekartik_http_redirect_client_browser_test
description: Browser tests
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.18.0 <4.0.0'

dependencies:
  tekartik_test_menu_browser:
    git:
      url: https://github.com/tekartik/test_menu.dart
      path: test_menu_browser
      ref: dart2_3
    version: '>=0.4.7'
  tekartik_http_redirect:
    path: ../http_redirect
  http:

dev_dependencies:
  build_runner: '>=2.1.4'
  build_web_compilers: '>=3.2.1'
  lints: '>=2.0.0'

