name: tekartik_http_redirect_client_browser_test
description: Browser tests
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.9.0

dependencies:
  tekartik_test_menu_browser:
    git:
      url: https://github.com/tekartik/test_menu.dart
      path: test_menu_browser
    version: '>=0.4.7'
  tekartik_http_redirect:
    path: ../http_redirect
  http:

dev_dependencies:
  build_runner: ">=2.4.13"
  build_web_compilers: ">=4.0.11"
  lints: ">=5.0.0"
resolution: workspace

