name: tekartik_http_redirect
description: Http redirect server and client
version: 0.8.0
publish_to: none

environment:
  sdk: ^3.9.0

dependencies:
  tekartik_http:
    git:
      url: https://github.com/tekartik/http.dart
      path: http
    version: '>=0.5.0'
  tekartik_http_io:
    git:
      url: https://github.com/tekartik/http.dart
      path: http_io
    version: '>=0.5.0'
  tekartik_common_utils:
    git:
      url: https://github.com/tekartik/common_utils.dart
  args: ">=2.6.0"
  http:
  path: ">=1.9.0"
  async:


dev_dependencies:
  dev_test: ">=1.0.0+4"
  test: ">=1.24.0"
  build_test:
  # build_node_compilers: ">=0.2.2"
  # build_web_compilers: ">=0.4.2"
  process_run: ">=1.2.1+1"
resolution: workspace

