name: tekartik_http_redirect
description: Http redirect server and client
version: 0.8.0
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  tekartik_http:
    git:
      url: https://github.com/tekartik/http.dart
      path: http
      ref: dart3a
    version: '>=0.5.0'
  tekartik_http_io:
    git:
      url: https://github.com/tekartik/http.dart
      path: http_io
      ref: dart3a
    version: '>=0.5.0'
  tekartik_common_utils:
    git:
      url: https://github.com/tekartik/common_utils.dart
      ref: dart3a
  args: '>=2.0.0'
  http:
  path:
  async:


dev_dependencies:
  dev_test: '>=0.15.0'
  test: '>=1.16.0'
  build_test:
  # build_node_compilers: ">=0.2.2"
  # build_web_compilers: ">=0.4.2"
  process_run: '>=0.12.0'

