name: tekartik_http_firestore_redirect
description: Http to firestore redirect
version: 1.0.0
publish_to: none
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  tekartik_http_redirect:
    git:
      url: git://github.com/tekartik/http_redirect.dart
      path: packages/http_redirect
      ref: null_safety
    version: '>=0.0.1'
  tekartik_firebase_firestore_sembast:
    git:
      url: git://github.com/tekartik/firebase_firestore.dart
      path: firestore_sembast
      ref: null_safety
    version: '>=0.8.0'
  tekartik_app_http:
    git:
      url: git://github.com/tekartik/app_common_utils.dart
      ref: null_safety
      path: app_http
    version: '>=0.1.0'
dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0

dependency_overrides:
  tekartik_http_redirect:
    path: ../http_redirect