name: tekartik_http_firestore_redirect
description: Http to firestore redirect
version: 1.0.0
publish_to: none
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  http:
  path:
  cv:
  tekartik_http_redirect:
    git:
      url: https://github.com/tekartik/http_redirect.dart
      path: packages/http_redirect
      ref: dart2_3
    version: '>=0.0.1'
  tekartik_firebase_firestore_sembast:
    git:
      url: https://github.com/tekartik/firebase_firestore.dart
      path: firestore_sembast
      ref: dart2_3
    version: '>=0.8.0'
  tekartik_app_http:
    git:
      url: https://github.com/tekartik/app_common_utils.dart
      ref: dart2_3
      path: app_http
    version: '>=0.1.0'
  tekartik_app_cv_firestore:
    git:
      url: https://github.com/tekartik/app_common_utils.dart
      ref: dart2_3
      path: app_cv_firestore
    version: '>=0.1.0'
dev_dependencies:
  test: ^1.16.0
  tekartik_http_redirect_test:
    git:
      url: https://github.com/tekartik/http_redirect.dart
      path: packages/http_redirect_test
      ref: dart2_3
    version: '>=0.0.1'
dependency_overrides:
  tekartik_http_redirect:
    path: ../http_redirect
  tekartik_http_redirect_test:
    path: ../http_redirect_test