name: tekartik_http_firestore_redirect
description: Http to firestore redirect
version: 1.0.0
publish_to: none
# homepage: https://www.example.com

environment:
  sdk: ^3.9.0

dependencies:
  http:
  path: ">=1.9.0"
  cv: ">=1.1.0+4"
  tekartik_http_redirect:
    git:
      url: https://github.com/tekartik/http_redirect.dart
      path: packages/http_redirect
      ref: dart3a
    version: '>=0.0.1'
  tekartik_firebase_firestore_sembast:
    git:
      url: https://github.com/tekartik/firebase_firestore.dart
      path: firestore_sembast
      ref: dart3a
    version: '>=0.8.0'
  tekartik_app_http:
    git:
      url: https://github.com/tekartik/app_common_utils.dart
      ref: dart3a
      path: app_http
    version: '>=0.1.0'
  tekartik_app_cv_firestore:
    git:
      url: https://github.com/tekartik/app_common_utils.dart
      ref: dart3a
      path: app_cv_firestore
    version: '>=0.1.0'
dev_dependencies:
  test: ">=1.24.0"
  tekartik_http_redirect_test:
    git:
      url: https://github.com/tekartik/http_redirect.dart
      path: packages/http_redirect_test
      ref: dart3a
    version: '>=0.0.1'

resolution: workspace
