name: http_redirect_repo_support
version: 0.1.0
publish_to: none
deploy_to: none

environment:
  sdk: ^3.7.0

dependencies:
  process_run: ">=1.2.1+1"
  path: ">=1.9.0"
dev_dependencies:
  test: ">=1.24.0"
  dev_build: ">=1.1.2"
  lints: ">=5.0.0"

resolution: workspace
#  tekartik_build_utils:
#    path: ../../../tekartik/build_utils.dart
