name: http_redirect_repo_support
version: 0.1.0
publish_to: none
deploy_to: none

environment:
  sdk: '>=3.4.0-0 <4.0.0'

dependencies:
  process_run: '>=0.10.0'
  path:
dev_dependencies:
  test: '>=1.0.0'
  dev_build: '>=0.13.4-dev.1'
  lints: '>=2.0.0'

dependency_overrides:
#  tekartik_build_utils:
#    path: ../../../tekartik/build_utils.dart
